name: Website Health Monitor

on: [push]

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v3

      - name: Run Lighthouse Test (Easy Mode)
        uses: treosh/lighthouse-ci-action@v12
        with:
          # Ye folder scan karega (jahan index.html hai)
          staticDistDir: ./
          # Report ka link generate karega
          temporaryPublicStorage: true
          # Artifacts save karega
          uploadArtifacts: true
